language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 7c1f599bb21502a8b45df160bcf898fa7fe86752
 local_dir: dist
 on:
   branch: master